### ISSUE TITLE
Proposal: Change the package name for the code and tests

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/pipeline-as-yaml-plugin#20]
Currently the code uses the `org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline;` package. A few concerns there:

* `org.jenkinsci.plugins.workflow` is an old root for Pipeline plugins. Maybe it makes sense to use `io.jenkins.plugins.pipeline`
* `multibranch` does not seem to be needed, the code does not really depend on MultiBranch logic

If we do the change, it needs to happen before 1.0 release. It will be a breaking change, and I doubt it makes sense to spend time on data migration logic to prevent that.

**Comment by aytuncbeken** [comment]
Make sense, I will make the package change to ```io.jenkins.plugins.pipeline```

**Comment by aytuncbeken** [comment]
Hi @oleg-nenashev ,

I made the changes and publish it soon. Thanks for the suggestion.

**Comment by oleg-nenashev** [comment]
Thank you!

**Comment by aytuncbeken** [comment]
Released with 0.14-rc
