### ISSUE TITLE
Can't save custom script path

### ISSUE THREAD

**Issue by maxenceledore** [jenkinsci/pipeline-as-yaml-plugin#34]
**Describe the bug**
When job Pipeline settings is set to 'Pipeline As Yaml from SCM' and a custom path to the Jenkinsfile.yaml is given, the location is not saved even after hitting the 'Save' button.

1. Create a new job
2. Setup the pipeline section with 'Pipeline As Yaml from SCM' and feed it with SCM/repo/credentials/branch and script path, if Jenkinsfile.yaml is in a subdirectory of a (git) projet.
3. Click Save
4. If you check the job configuration again, everything is fine except that the specified path as been replaced by "Jenkinsfile.yaml"

**Expected behavior**
A script path location taken into account

**Versions:**
 - Jenkins Version : 2.249.2
 - plugin version : 0.12-rc

**Comment by aytuncbeken** [comment]
Hi @maxenceledore 
Thank you for reporting this bug. It seems there is a problem on UI definitions. It will be fixed in the next release.

**Comment by aytuncbeken** [comment]
Released with 0.14-rc
