### ISSUE TITLE
scenarioInput stage missing close brace

### ISSUE THREAD

**Issue by keqingyuan** [jenkinsci/pipeline-as-yaml-plugin#36]
**Describe the bug**
scenarioInput stage missing close brace

**Additional context**
pipeline {
  agent none
  stages {
    stage('Stage1') {
      input {
        message "message"
        id "id"
        ok "ok"
        submitter "submitter"
        submitterParameter "submitterParameter"
        parameters {
          string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        }
      steps {
        echo "1"
      }
    }
  }
}

**Comment by aytuncbeken** [comment]
Hi @keqingyuan 

Could you please write the yaml format of this output ? 

Thanks

**Comment by keqingyuan** [comment]
below
-------
pipeline:
  stages:
    - stage: "Stage1"
      input:
        message: "message"
        id: "id"
        ok: "ok"
        submitter: "submitter"
        submitterParameter: "submitterParameter"
        parameters:
          - "string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')"
      steps:
        - echo "1"

**Comment by aytuncbeken** [comment]
Hi @keqingyuan 
Thank you for pointing out this bug. Made the changes, will be fixed with the new release.
