### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by wdcossey** [jenkinsci/pipeline-as-yaml-plugin#64]
Hi everyone,

I just wanted to know what the status of this project is.

We (the company) will be moving to Jenkins in the near future and the devs have been looking at how to best migrate our existing pipelines (in Azure DevOps and TeamCity).

I understand that this project is currently in `incubation` but I haven't seen much activity on the repository (esp. Releases).

**Comment by iman4000** [comment]
@oleg-nenashev can you update us please?

**Comment by leopck** [comment]
any update on this?

**Comment by Bargamut** [comment]
I use this plugin in my home project - everything is fine for me. **But** plugin have deprecated dependency: #70 

So I have the same question: is this project alive? ))
This plugin is cool but seems like this project have forgotten 2 years ago..

**Comment by jessie828** [comment]
Any update?

**Comment by Crown0815** [comment]
Any updates?

**Comment by jonesbusy** [comment]
Most likely abandoned. Anyone is free to adopt it a maintain it and make it evolve

I will at at least to make it work with recent Jenkins version, but not to add new feature (at least for now).

Regards,

**Comment by slide** [comment]
I would like to adopt this plugin, I'll send the request via developers list, but I think a label needs to be added to show that the plugin is up for adoption.

**Comment by jonesbusy** [comment]
@slide 

I adopted it few month ago because it was abandoned and broken because of outdated dependencies (SnakeYAML etc...)

I'm now maintainer of it just to keep it in a minimal working state but not planning to make it evolve for now

I'm more than happy I you would like to join as maintainer as well

**Comment by slide** [comment]
Awesome, I misunderstood your comment. I'll file a repository permissions PR and tag you to approve.

**Comment by slide** [comment]
I'm going to close this out, the project is still alive. I am looking at implementing some of the features in the issues and fixing things up.
