### ISSUE TITLE
Deprecated dependency: "Pipeline: Deprecated Groovy Libraries"

### ISSUE THREAD

**Issue by Bargamut** [jenkinsci/pipeline-as-yaml-plugin#70]
Hi there! )

This plugin have deprecated dependency: `Pipeline: Deprecated Groovy Libraries`.
https://plugins.jenkins.io/workflow-cps-global-lib/

The plugin page have link to actual plugin - https://plugins.jenkins.io/pipeline-groovy-lib/

Do you have a plan to update your deps?

**Comment by Withy14** [comment]
This needs to be solved I think. The point is that while this feature is amazing it is not possblle for it to have deprecated dependency, am I rightt?

**Comment by slide** [comment]
Looks like this has been addressed. I'm going to close this out. Please reopen if this is not the case.
